name: App Inspect API

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    appinspect:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - uses: actions/cache@v4
              with:
                  path: node_modules
                  key: nodeModules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      nodeModules-
            - name: Update Version Number
              run: |
                old_str="X.Y.Z"
                new_str=$(echo "${GITHUB_REF#refs/*/}" | tr -d "v")
                sed -i "s/$old_str/$new_str/g" package.json
                sed -i "s/$old_str/$new_str/g" ./github_dashboard_collection/default/app.conf
                cat package.json
                cat ./github_dashboard_collection/default/app.conf
            - name: Install dependencies
              run: yarn install
              env:
                  CI: true
            - name: Build app package
              run: |
                  yarn package
                  mv dist/*.spl dist/github_dashboard_collection.spl
            - uses: actions/upload-artifact@v4
              with:
                  name: app-package
                  path: dist/github_dashboard_collection.spl
            - uses: ./.github/actions/appinspect_api
              with:
                  filePath: ./dist/github_dashboard_collection.spl
                  splunkUser: ${{ secrets.SPLUNKBASE_USER }}
                  splunkPassword: ${{ secrets.SPLUNKBASE_PASSWORD }}
                  includedTags: cloud
            - name: Release
              uses: fnkr/github-action-ghr@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GHR_PATH: ./dist/github_dashboard_collection.spl
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish App to Splunkbase
              uses: ./.github/actions/appinspect_publish # Uses an action in the root directory
              with:
                APP_ID: '8703'
                APP_FILE: './dist/github_dashboard_collection.spl'
                SPLUNK_USERNAME: ${{ secrets.SPLUNKBASE_USER }}
                SPLUNK_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
                SPLUNK_VERSION: '9.0,9.1,9.2,9.3,9.4,10.0,10.1,10.2,10.3,10.4,10.5'
                VISIBILITY: 'true'
