name: Send Workflow Logs to Splunk

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Actions workflow run ID to log'
        required: true
        type: string
      workflow_name:
        description: 'Name of the workflow that completed'
        required: false
        type: string

permissions:
  actions: read
  contents: read

env:
  triggerID: ${{ inputs.run_id }}
  triggerJob: ${{ inputs.workflow_name }}

jobs:
  WriteLogs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Output Job ID
        run: echo ${{ inputs.run_id }}

      - name: Send Workflow logs to Splunk
        if: ${{ always() }}
        uses: ./.github/actions/log_to_splunk
        with:
          splunk-url: ${{ secrets.HEC_URL }}
          hec-token: ${{ secrets.HEC_TOKEN }}
          github-token: ${{ github.token }}
          workflowID: ${{ env.triggerID }}
          source: ${{ env.triggerJob }}
