name: Send Workflow Trace to Splunk Observability

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  ExportTrace:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.workflow_run.name != 'Send Workflow Trace to Splunk Observability'
      && github.event.workflow_run.name != 'Send Workflow Logs to Splunk' }}
    steps:
      - name: Export workflow run to Splunk Observability Cloud
        uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: https://ingest.${{ secrets.SFX_REALM }}.signalfx.com/v2/trace/otlp
          otlpHeaders: "X-SF-Token=${{ secrets.SPLUNK_ACCESS_TOKEN }}"
          otelServiceName: github_dashboard_collection
          githubToken: ${{ github.token }}
          runId: ${{ github.event.workflow_run.id }}
