name: Send Workflow Telemetry to Splunk

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Actions workflow run ID to log and trace'
        required: true
        type: string
      workflow_name:
        description: 'Name of the workflow that completed'
        required: false
        type: string

permissions:
  actions: read
  contents: read

jobs:
  WriteLogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send Workflow logs to Splunk
        if: ${{ always() }}
        uses: ./.github/actions/log_to_splunk
        with:
          splunk-url: ${{ secrets.HEC_URL }}
          hec-token: ${{ secrets.HEC_TOKEN }}
          github-token: ${{ github.token }}
          workflowID: ${{ inputs.run_id }}
          source: ${{ inputs.workflow_name }}

  ExportTrace:
    runs-on: ubuntu-latest
    steps:
      - name: Export workflow run to Splunk Observability Cloud
        uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: https://ingest.${{ secrets.SFX_REALM }}.signalfx.com/v2/trace/otlp
          otlpHeaders: "X-SF-Token=${{ secrets.SPLUNK_ACCESS_TOKEN }}"
          otelServiceName: github_dashboard_collection
          extraAttributes: "deployment.environment=github-actions"
          githubToken: ${{ github.token }}
          runId: ${{ inputs.run_id }}
